import Head from "next/head";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Text,
  Input,
  InputGroup,
  InputRightElement,
  Center,
} from "@chakra-ui/react";

import { IoSend } from "react-icons/io5";

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat for me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Box width={"full"} display={"flex"} flexDirection={"column"} height={"full"} gap={5}>
          <Box flex={1}>
            <Box border={"1px solid white"} w={"50%"} display={"inline-block"}>
              <Text>Đến khi nào em mới biết bỏ thuốc nhở</Text>
            </Box>
          </Box>
          <Box>
            <InputGroup>
              <Input minHeight={"50px"} color="white" borderRadius={"50px"} />

              <InputRightElement height={"full"}>
                <IoSend color="white" />
              </InputRightElement>
            </InputGroup>
          </Box>
        </Box>
      </main>
    </>
  );
}
